### PR TITLE
Conditionally render "List" and "Add Item" NavLinks on `List` and `AddItem` views and remove NavLinks from `Home` view

### LINKED ISSUE #49: 26. Prevent access to `AddItem` page without list token
### Summary
Currently a user can navigate to the `AddItem` page when there is no token. If the user tries to submit an item, they receive an error message. We want to restrict access to the `AddItem` page so it's only viewable when there is a list token.

### Acceptance Criteria
- [x] If there is no list token and the user clicks on the `Add Item` link or enters "/add-item" in the URL bar, the `Home` view persists.
- [x] If the user creates a new list or enters a list token and clicks on the `Add Item` link or enters "/add-item" in the URL bar, they are redirected to the `AddItem` page.

### PR DESCRIPTION
**Pull request by emilysellers**
## Description
Before this PR, a user could navigate to the `AddItem` page when there is no token. If the user tried to submit an item, they received an error message. Additionally, on the `Home` view, links to "Home" and "List" were displayed, but did not link to another location.

This PR implements the following:
- removes "Home", "Add Item" and "List" links from nav bar on `Home` view
- checks for a token before rendering "List" and "Add Item" links in the nav bar on the `List` and `AddItem` views

## Related Issue
Closes #49 

## Acceptance Criteria
- [x]  If there is no list token and the user clicks on the "Add Item" link or enters "/add-item" in the URL bar, the `Home` view persists.
- [x]  If the user creates a new list or enters a list token and clicks on the "Add Item" link or enters "/add-item" in the URL bar, they are redirected to the `AddItem` page.

## Type of Changes
|     | Type                       |
| --- | -------------------------- |
|  ✓  | :bug: Bug fix              |
|     | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before
This before video shows that a user was able to navigate to the `AddItem` page without a list token. If they try to submit an item, they receive an error message. Also, "Home" and "List" links appear on the `Home` view but do not link anywhere.

https://github.com/the-collab-lab/tcl-57-smart-shopping-list/assets/84364905/e82dd07d-8b94-4c0d-97a9-5ea0d07a8cfa

### After
This after video shows that there is no token in local storage and no links appear in the nav bar on the `Home` view. Then the user creates a new list and is redirected to the `List` view. Links for "Add Item" and "List" appear in the nav bar and each link navigates to the corresponding view.

https://github.com/the-collab-lab/tcl-57-smart-shopping-list/assets/84364905/4dfc85b9-f66f-49aa-88b1-822d0040e8fd

## Testing Steps / QA Criteria
- Visit the preview URL for this PR: https://tcl-57-smart-shopping-list--pr51-es-restrict-add-item-f6zh67km.web.app/
- If there is a token in local storage, delete it. You should see the `Home` view without any links in the nav bar.
- Create a list or enter a list token. You should be redirected to the `List` view. Check that "List" and "Add Item" links display in the nav bar on the `List` and `AddItem` views, and that those links navigate to the correct page.

### CODE REVIEW

**Review by jongranados — APPROVED** [review]
Working as expected! Much more reasonable behavior. Approved.

I do wonder, though, if the user should even be presented the Add-Item nav element if a token does not exist. Another idea would be to keep the Add-Item nav element but present a Toast prompting them to create a new list before they can add an item. Thinking out loud here.

**Comment by emilysellers** [comment]
> Working as expected! Much more reasonable behavior. Approved.
> 
> I do wonder, though, if the user should even be presented the Add-Item nav element if a token does not exist. Another idea would be to keep the Add-Item nav element but present a Toast prompting them to create a new list before they can add an item. Thinking out loud here.

Good point, @jongranados. I've been wondering about the purpose of displaying any nav links at all on the `Home` view, since none of them actually link anywhere... 

I just pushed a commit that removes the nav links from the `Home` view and then checks for a `listToken` before displaying the "List" and "Add Item" links, so those links display on the `List` and `AddItem` views. The "Home" link doesn't display at all, since (in the current state of our app and it's functionality) it never actually functions as a link. Very curious to hear everyone's thoughts on this! @Amy-Pr  @bethmelmtv

**Review by jongranados — APPROVED** [review]
Awesome work Emily! Such a subtle detail from the user's POV but one that really elevates the user experience in my opinion. It reminds me of Charles Eames' quote: "The details are the thing." (or something like that 😂).

**Comment by Amy-Pr** [comment]
I think this is great from a user standpoint.  I was going to add an menu icon for the small screen version to contain the links so they don't wrap so funny. I don't know how this change will affect that though. Especially since now we'll only have 2 links. I think we should merge this first.

**Review by Amy-Pr — APPROVED** [review]

**Review by Amy-Pr — COMMENTED** [review]
Oh, wait I just thought of something. What if the user wants to join a different list or create a new list? My guess is that would require an entirely new feature? Since for now the only way to do that is to delete the token from the browser?

**Comment by emilysellers** [comment]
> Oh, wait I just thought of something. What if the user wants to join a different list or create a new list? My guess is that would require an entirely new feature? Since for now the only way to do that is to delete the token from the browser?

Right, I think we'd need to implement a button or something to clear the token and route back to the home page... which would definitely be a nice feature!

**Pull request merged**
