### PR TITLE
update Layout.js links with NavLinks which navigate to appropriate pages

### LINKED ISSUE #2: 2. As a user, I want to be able to navigate to all the pages in the application by clicking the links in the nav bar
## Summary

Users need to be able to navigate between the pages of our application in order to access all of its features. There is a navigation bar in the `Layout.jsx` component, but it's not quite feature-complete: the links in the nav element don't actually allow the user to navigate from page to page.

## Acceptance criteria
- [x] The `nav` element is added to the `Layout` component
- [x] Links to the "Home", "List", and "Add item" pages of the app are In the `nav` element
- [x] The links all function as expected using  the `NavLink` component from `react-router-dom`

## Notes
- The [official docs for the `NavLink` component](https://reactrouterdotcom.fly.dev/docs/en/v6/components/nav-link) will come in very handy!
- While a standard anchor element (`<a>`) _could_ allow a user to navigate from page to page, the `NavLink` component adds additional behavior that is essential to our app functioning correctly!

### PR DESCRIPTION
**Pull request by bethmelmtv**
_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description

This PR completes an existing component to navigate through the pages of our application. 

Inside the Layouts component, we imported and used NavLink from react-router-dom, which is an element that allows a user to navigate to another page by clicking on the link. 

We completed the Layout function in Layout.jsx by adding URLs to the NavLinks to the "home page", "list page", and "add items" page. 

Check out more documentation on how to use NavLinks [here](https://reactrouter.com/en/main/components/nav-link).  

## Related Issue

closes #2

## Acceptance Criteria

- [x]  The nav element is added to the Layout component
- [x]  Links to the "Home", "List", and "Add item" pages of the app are In the nav element
- [x]  The links all function as expected using the NavLink component from react-router-dom

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

https://user-images.githubusercontent.com/84364905/230506639-3d13408c-d415-424f-b078-daed2dce56d6.mov

## Testing Steps / QA Criteria

- From your terminal, pull down this branch with git pull origin bm-es-nav-links and check that branch out with git checkout bm-es-nav-links.
- Then npm i to install the newly added dependencies locally and npm start start to launch the app.
- Click on each item in the navigation (Home, List, Add Item) and it should reroute you to each corresponding page.

### CODE REVIEW

**Review by Amy-Pr — APPROVED** [review]
All of the links work on my end. No issues with the code. Nice work.

**Review by danainjax — APPROVED** [review]
This looks great, you two! Approved 😁 In your next pr, you can include details re: acceptance criteria, description, etc.

**Review by djtaylor8 — APPROVED** [review]
Nice work!

**Comment by emilysellers** [comment]
> This looks great, you two! Approved 😁 In your next pr, you can include details re: acceptance criteria, description, etc.

Thanks @danainjax ! We've just added some more details to our PR.

**Comment by danainjax** [comment]
@emilysellers @bethmelmtv 
Outstanding work! And I love the addition of the video!

**Pull request merged**
